// client/src/pages/Homepage.jsx
import React from 'react';
import { Link } from 'react-router-dom';

import { LimitedBookList } from '../components/BookList';


const Homepage = () => {
  return (
    <div>
      <h1>Welcome to the Book Club Hub</h1>
      <p>Your ultimate platform for book clubs!</p>
      <Link to="/users">View All Users</Link> {/* Link to the user list */}
    
      <h1>Latest Books</h1>
      <LimitedBookList />
    </div>
  );
};

export default Homepage;

// client/src/pages/HomePage.vue
<template>
    <div>
        <h1>Welcome to the Book Club Hub</h1>
        <p>Your ultimate platform for book clubs!</p>
        <!-- Link to the user list -->
        <router-link to="/users">View All Users</router-link>

        <h1>Latest Books</h1>
        <LimitedBookList />
    </div>
</template>

<script>
import LimitedBookList from '@/components/LimitedBookList.vue';

export default {
    name: 'HomePage',
    components: {
        LimitedBookList,
    },
};
</script>
