// client/src/pages/UserProfile.jsx
import { useQuery } from "@apollo/client";
import { GET_USER_BY_ID } from "../utils/queries/userQueries";
import { useParams } from "react-router-dom";

const UserProfile = () => {
    const { userId } = useParams(); // Get the user ID from the URL parameters
    const { loading, error, data } = useQuery(GET_USER_BY_ID, {
        variables: { id: userId },
    });

    if (loading) return <p>Loading...</p>;
    if (error) return <p>Error: {error.message}</p>;

    const { username, email, friends } = data.user;

    return (
        <div>
            <h1>{username}'s Profile</h1>
            <p>Email: {email}</p>
            <h3>Friends:</h3>
            <ul>
                {friends.map((friend) => (
                    <li key={friend._id}>{friend.username}</li>
                ))}
            </ul>
        </div>
    );
};

export default UserProfile;

// client/src/pages/UserProfile.vue
<template>
    <div>
        <div v-if="loading">Loading...</div>
        <div v-if="error">Error: {{ error.message }}</div>
        <div v-if="data">
            <h1>{{ data.user.username }}'s Profile</h1>
            <p>Email: {{ data.user.email }}</p>
            <h3>Friends:</h3>
            <ul>
                <li v-for="friend in data.user.friends" :key="friend._id">
                    {{ friend.username }}
                </li>
            </ul>
        </div>
    </div>
</template>

<script>
import { useQuery } from '@vue/apollo-composable'; 
import { onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import { GET_USER_BY_ID } from '@/utils/queries/userQueries';

export default {
    name: 'UserProfile',
    setup() {
        const route = useRoute();
        const userId = route.params.userId;

        const loading = ref(true);
        const error = ref(null);
        const data = ref(null);

        const { result, loading: apolloLoading, error: apolloError } = useQuery(GET_USER_BY_ID, {
            variables: { id: userId },
        });

        onMounted(() => {
            loading.value = apolloLoading;
            error.value = apolloError;
            data.value = result;
        });

        return { loading, error, data };
    },
};
</script>
