// client/src/components/AddFriendButton/AddFriendButton.jsx
import React from 'react';
import { useMutation } from '@apollo/client';
import { ADD_FRIEND } from '@/utils/mutations/userMutations';

const AddFriendButton = ({ friendId }) => {
  const [addFriend] = useMutation(ADD_FRIEND);

  const handleAddFriend = async () => {
    try {
      await addFriend({ variables: { userId: 'loggedInUserId', friendId } });
      console.log('Friend added');
    } catch (err) {
      console.error('Error adding friend', err);
    }
  };

  return <button onClick={handleAddFriend}>Add Friend</button>;
};

export default AddFriendButton;

// client/src/components/AddFriendButton.vue
<template>
    <button @click="addFriend">Add Friend</button>
  </template>
  
  <script>
  import { useMutation } from '@vue/apollo-composable';
  import { ADD_FRIEND } from '@/utils/mutations/userMutations';
  
  export default {
    props: {
      friendId: {
        type: String,
        required: true,
      },
    },
    setup(props) {
      const { mutate: addFriend } = useMutation(ADD_FRIEND);
  
      const handleAddFriend = async () => {
        try {
          await addFriend({ userId: 'loggedInUserId', friendId: props.friendId });
          console.log('Friend added');
        } catch (err) {
          console.error('Error adding friend', err);
        }
      };
  
      return { addFriend: handleAddFriend };
    }
  };
  </script>
