// client/src/components/BookCard/BookCard.jsx
import Title from '../Title'

const BookCard = ({ book }) => {
    return (
        <div className="w-60">
            <Title tier={4} className='!text-left'>{book.title}</Title>
            <p>{book.author}</p>
            <p className="truncate">{book.description}</p>
            {book.image && <img src={book.image} alt={book.title} className="mx-auto" />}
        </div>
    );
};

export default BookCard;

// client/src/components/BookCard.vue
<template>
    <div>
        <h3>{{ book.title }}</h3>
        <p>{{ book.author }}</p>
        <p>{{ book.description }}</p>
        <img v-if="book.image" :src="book.image" :alt="book.title" />
    </div>
</template>

<script>
export default {
    name: 'BookCard',
    props: {
        book: {
            type: Object,
            required: true,
        },
    },
};
</script>
