// client/src/components/ClubCard/ClubCard.jsx
const ClubCard = ({ club }) => {
    // Default club object if none is provided
    const defaultClub = {
        error: "Club couldn't be displayed",
    };

    // Fallback to default club if club prop is not provided
    const currentClub = club || defaultClub;

    return (
        <div>
            {/* If there is no error, display club information */}
            {!currentClub.error ? (
                <div>
                    <h1>{currentClub.name}</h1>
                    <p>{currentClub.description}</p>
                    <p>Created by: {currentClub.founder?.username}</p>
                    <div>{currentClub.img || "Default Image"}</div>
                    <p>Members: {currentClub.memberCount}</p>
                </div>
            ) : (
                // If there is an error, display the error message
                <div>{currentClub.error}</div>
            )}
        </div>
    );
};

export default ClubCard;

// client/src/components/ClubCard.vue
<template>
    <div>
        <!-- If there is no error, display club information -->
        <div v-if="!club.error">
            <h1>{{ club.name }}</h1>
            <p>{{ club.description }}</p>
            <p>Created by: {{ club.founder.username }}</p>
            <div>{{ club.img || 'Default Image' }}</div>
            <p>Members: {{ club.memberCount }}</p>
        </div>

        <!-- If there is an error, display the error message -->
        <div v-else>
            {{ club.error }}
        </div>
    </div>
</template>

<script>
export default {
    name: 'ClubCard',
    props: {
        club: {
            type: Object,
            default: () => ({ error: "Club couldn't be displayed" })
        }
    }
};
</script>
