// client/src/components/BookList/LimitedBookList.jsx
import { useQuery, gql } from "@apollo/client";
import { Link } from "react-router-dom";
import BookCard from "../BookCard/BookCard";

const GET_X_BOOKS = gql`
    query Books($limit: Int) {
        books(limit: $limit) {
            _id
            title
            author
            description
            image
        }
    }
`;

const LimitedBookList = () => {
    const { loading, error, data } = useQuery(GET_X_BOOKS, {
        variables: { limit: 10 },
    });

    if (loading) return <p>Loading...</p>;
    if (error) return <p>Error: {error.message}</p>;

    return (
        <div>
            <ul>
                {data.books.map((book) => (
                    <li key={book._id}>
                        <Link to="/community">
                            <BookCard book={book} />
                        </Link>
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default LimitedBookList;

// client/src/components/LimitedBookList.vue
<template>
    <div>
        <div v-if="loading">Loading...</div>
        <div v-if="error">Error: {{ error.message }}</div>
        <ul v-if="data">
            <li v-for="book in data.books" :key="book._id">
                <router-link to="/community">
                    <BookCard :book="book" />
                </router-link>
            </li>
        </ul>
    </div>
</template>

<script>
import { useQuery } from '@vue/apollo-composable';
import { gql } from 'graphql-tag'; // Or you can use '@apollo/client/core'
import BookCard from '@/components/BookCard.vue';

const GET_X_BOOKS = gql`
    query Books($limit: Int) {
        books(limit: $limit) {
        _id
        title
        author
        description
        image
        }
    }`;

export default {
    name: 'LimitedBookList',
    components: {
        BookCard,
    },
    setup() {
        const { result, loading, error } = useQuery(GET_X_BOOKS, { limit: 10 });

        return {
            loading,
            error,
            data: result,
        };
    },
};
</script>
