// client/src/components/Navigation/Navigation.jsx
import { useContext } from "react";
import { Link } from "react-router-dom";

// Assuming UserContext is already created and provided higher up in the app
import { UserContext } from "../contexts/UserContext";

const Navigation = () => {
    // Access the UserContext
    const { user, setUser } = useContext(UserContext);

    // Function to handle logout
    const handleLogout = () => {
        setUser(null); // Set user to null, effectively logging out
        // Additional logout logic, such as clearing tokens or redirecting
    };

    return (
        <nav>
            <ul>
                <li>
                    <Link to="/">Home</Link>
                </li>
                <li>
                    <Link to="/book-clubs">Book Clubs</Link>
                </li>
                <li>
                    <Link to="/discussions/clubId">Discussions</Link>
                </li>
                <li>
                    <Link to="/reviews/bookId">Reviews</Link>
                </li>
                <li>
                    <Link to="/user-profile">Profile</Link>
                </li>
                {user ? (
                    <>
                        <li>
                            <Link to="/user-settings">Settings</Link>
                        </li>
                        <li>
                            <button onClick={handleLogout}>Logout</button>
                        </li>
                    </>
                ) : (
                    <>
                        <li>
                            <Link to="/login">Login</Link>
                        </li>
                        <li>
                            <Link to="/signup">Signup</Link>
                        </li>
                    </>
                )}
            </ul>
        </nav>
    );
};

export default Navigation;

// client/src/components/Navigation.vue
<template>
    <nav>
        <ul>
            <li><router-link to="/">Home</router-link></li>
            <li><router-link to="/book-clubs">Book Clubs</router-link></li>
            <li><router-link to="/discussions/clubId">Discussions</router-link></li>
            <li><router-link to="/reviews/bookId">Reviews</router-link></li>
            <li><router-link to="/user-profile">Profile</router-link></li>
            <li v-if="user">
                <router-link to="/user-settings">Settings</router-link>
                <button @click="handleLogout">Logout</button>
            </li>
            <li v-else>
                <router-link to="/login">Login</router-link>
                <router-link to="/signup">Signup</router-link>
            </li>
        </ul>
    </nav>
</template>

<script>
import { inject } from 'vue';

export default {
    name: 'Navigation',
    setup() {
        // Access the UserContext using inject
        const { user, setUser } = inject('UserContext');

        // Function to handle logout
        const handleLogout = () => {
            setUser(null); // Set user to null, effectively logging out
            // Additional logout logic like clearing tokens or redirecting
        };

        return {
            user,
            handleLogout,
        };
    },
};
</script>
