// client/src/components/UserCard/UserCard.jsx


const UserCard = ({ user, onAddFriend, loggedInUserId }) => {
  return (
    <div className="user-card">
      <h2>{user.username}</h2>
      <p>Email: {user.email}</p>
      <button
        onClick={() => onAddFriend(user._id)}
        disabled={!loggedInUserId} // Disable button if no user is logged in
      >
        Add Friend
      </button>
    </div>
  );
};

export default UserCard;

// client/src/components/UserCard.vue
<template>
    <div>
      <h3>{{ user.username }}</h3>
      <p>{{ user.email }}</p>
      <AddFriendButton :friendId="user._id" />
    </div>
  </template>
  
  <script>
  import AddFriendButton from './AddFriendButton.vue';
  
  export default {
    name: 'UserCard',
    props: {
      user: {
        type: Object,
        required: true,
      },
    },
    components: {
      AddFriendButton,
    },
  };
  </script>
